---
language: go
go:
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -v ./...
  - golint ./...
  - go vet -x ./...
  - $HOME/gopath/bin/goveralls -repotoken upzfVue6EK7lrHAQMZX5vIMmd2kwXv1XC
