---
language: go
go:
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - go test -v ./...
  - golint ./...
  - go vet -x ./...
